# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Jeremy Conkin"

# Tagline next to the site title
tagline: "Digital Product Development"

# A description of your site for social meta tag, search engines, and feed.xml
description: "I love custom user experiences and helping delivery teams be their best."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# Sass
sass:
  sass_dir: _sass
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://jeremyconkin.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
#disqus: "justgoodthemes"

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Author information - author info at the bottom of the post
author_name: "Jeremy"
author_bio: "John is a designer, photographer, speaker, author of a couple of books about typography and the founder of photo magazine Curious."
author_url:  "https://jeremyconkin.com"
author_location: "Denver, Colorado"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "https://jeremyconkin.com"
banner_image: images/banner.jpg
banner_image_alt: "Alt text"

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_url: "https://twitter.com/jeremyconkin"
github_url: "https://github.com/jeremyconkin/"
medium_url: "https://medium.com/@jeremyconkin"
instagram_url: "https://www.instagram.com/jeremyconkin"
linkedin_url: "https://www.linkedin.com/in/jeremyconkin/"

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
